import type {
    FormLoadedResult,
    LoadExtensionInput,
    PortalLoadedResult,
    SaveFormInput,
} from '../src/runtime/index.js';

/** Complete synthetic settings with the canonical public response shape. */
export const publicFormFields =
    (): FormLoadedResult['payload']['publicFields'] => ({
        type: 'form',
        state: {
            formFields: null,
            tableId: 'table_example',
            disableCreatingRecords: null,
            disableAccessingExistingRecords: null,
            accessingRecordsMethod: null,
            loginFields: null,
            ifRecordDoesNotExist: null,
            enableCustomErrorMessage: null,
            customErrorMessageIfRecordDoesNotExist: null,
            redirectUrlIfRecordDoesNotExist: null,
            allowLoginConditionally: null,
            allowLoginConditionFields: {
                logicalOperator: 'and',
                conditions: [],
            },
            enableAccessingExistingRecordsConditionally: null,
            enableAccessingExistingRecordsConditionFields: null,
            allowCreatingOnlyOneRecord: null,
            disableFormAfterSubmissionLimit: null,
            submissionLimit: null,
            enableLockingFormAfterSubmission: null,
            checkboxFieldUsedForLocking: null,
            disableFormAtScheduledDate: null,
            dateForDisablingFormStatic: null,
            dateForDisablingFormField: null,
            dateForDisablingFormType: null,
            enableCustomFormDisabledMessage: null,
            formDisabledMessageStatic: null,
            formDisabledMessageField: null,
            formDisabledMessageType: null,
            enableSaveFormButtonConditionally: null,
            enableSaveFormButtonConditionFields: null,
            customDisabledFormMessage: null,
            embeddedFormRedirectType: null,
            enableCustomExtensionSlug: null,
            enableLoginPageTitle: null,
            loginPageTitle: null,
            enableLoginPageSubtitle: null,
            loginPageSubtitle: null,
            enableLoginPageCoverImage: null,
            loginPageCoverImageURL: null,
            loginPageImageFit: null,
            enableLoginPageCustomSubmitButtonLabel: null,
            loginPageSubmitButtonLabel: null,
            formHeaderTitleType: null,
            formHeaderTitleField: null,
            formTitleDescriptionStatic: null,
            enableFormDescription: null,
            formHeaderDescriptionStatic: null,
            formHeaderDescriptionField: null,
            formHeaderDescriptionType: null,
            truncateDescription: null,
            enableLogo: null,
            formHeaderLogoImageURLStatic: null,
            formHeaderLogoImageURLField: null,
            formHeaderLogoImageURLType: null,
            enableCoverImage: null,
            formCoverImageUrl: null,
            enableFormFooter: null,
            formFooterDescriptionStatic: null,
            formFooterDescriptionField: null,
            formFooterDescriptionType: null,
            enableSubmitButtonLabel: null,
            formSaveButtonText: null,
            promptUserBeforeSubmission: null,
            successAction: null,
            successMessageStatic: null,
            successMessageField: null,
            successMessageType: null,
            successMessageDelay: null,
            afterFormSubmission: null,
            reloadFormDelay: null,
            showPrintButton: null,
            successMessageCanCreateNewRecord: null,
            successMessageNewRecordText: null,
            allowCopySubmittedToNewForm: null,
            allowCopySubmittedToNewFormButtonText: null,
            redirectURLType: null,
            redirectURLField: null,
            redirectURLStatic: null,
            enableRedirectDelay: null,
            redirectDelay: null,
            enableWebhookTrigger: null,
            webhookTriggerURLType: null,
            webhookTriggerURLField: null,
            webhookTriggerURLStatic: null,
            webhookURLRequestType: null,
            webhookTriggerConditions: null,
            sessionExpiration: null,
            closeDelay: null,
            emailFormSubmissionToAdmin: null,
            formSubmissionEmails: null,
            emailFormSubmissionToUser: null,
            emailFormSubmissionToUserEmailField: null,
            emailFormSubmissionToUserEmailSubjectField: null,
            emailFormSubmissionToUserEmailBodyField: null,
            emailFormSubmissionToUserEmailFrom: null,
            sendSMSConfirmationToUser: null,
            smsPhoneNumberField: null,
            smsMessageField: null,
            themeColor: null,
            setFormBackgroundColorToThemeColor: null,
            hideGridHeaderIcons: null,
            formMaxWidth: null,
            multiPageFormMode: null,
            language: null,
            enableExtensionPassword: null,
            extensionPassword: null,
            enableCaptcha: null,
            allowDeletingRecords: null,
            hideDeleteButton: null,
            deleteButtonText: null,
            enableTracking: null,
            userIPAddressField: null,
            userLongitudeField: null,
            userLatitudeField: null,
            enablePrefillForNewRecords: null,
            prefillURLParamsForAddingRecords: null,
            allowHiddenPrefills: null,
            autoSubmitAfterPrefill: null,
            enableFormComputeMode: null,
            computeMode: null,
            enableCustomComputeButtonLabel: null,
            computeModeComputeButtonTitle: null,
            computeModeUseConfirmationCheckbox: null,
            computeModeConfirmationCheckboxField: null,
            sendUpdateLinkToUser: null,
            updateLinkEmailField: null,
            saveFormProgress: null,
            enableCommentsOnChildForms: null,
            commenterNameField: null,
            enableIntercomChat: null,
            intercomAppId: null,
            goToNextRecordAfterSubmission: null,
        },
    });

export const publicPortalFields =
    (): PortalLoadedResult['payload']['publicFields'] => ({
        type: 'portal',
        state: {
            portalFields: null,
            tableId: 'table_example',
            enableCustomExtensionSlug: null,
            doNotRequireLoginInPortal: null,
            loginFields: null,
            ifRecordDoesNotExist: null,
            redirectUrlIfRecordDoesNotExist: null,
            enableCustomErrorMessage: null,
            customErrorMessageIfRecordDoesNotExist: null,
            allowLoginConditionally: null,
            allowLoginConditionFields: null,
            lastLoginDate: null,
            enableLoginPageTitle: null,
            loginPageTitle: null,
            enableLoginPageSubtitle: null,
            loginPageSubtitle: null,
            enableLoginPageCoverImage: null,
            loginPageCoverImageURL: null,
            loginPageImageFit: null,
            enableLoginPageCustomSubmitButtonLabel: null,
            loginPageSubmitButtonLabel: null,
            portalPageTitle: null,
            hidePortalHeader: null,
            portalHeaderTitleType: null,
            portalHeaderTitleField: null,
            showPortalHeaderAsHTML: null,
            portalHeaderLogo: null,
            enablePortalDescription: null,
            portalDescription: null,
            enablePortalWelcomeMessage: null,
            portalWelcomeMessage: null,
            truncatePortalDescription: null,
            doNotShowUserProfile: null,
            portalUserMenu: null,
            portalProfileTitleType: null,
            portalHeaderUserTitleField: null,
            portalHeaderUserTitleText: null,
            extensionIdForUserProfile: null,
            hideLogoutButton: null,
            hideMenuItems: null,
            portalHeaderDisplayMode: null,
            viewsDisplayMode: null,
            enableExternalLinks: null,
            menuItems: null,
            groupMenus: null,
            menusGroupName: null,
            enableExtensionPassword: null,
            extensionPassword: null,
            themeColor: null,
            setFormBackgroundColorToThemeColor: null,
            hideGridHeaderIcons: null,
            childFormMaxWidth: null,
            language: null,
            enableCommentsOnChildForms: null,
            commenterNameField: null,
            enableIntercomChat: null,
            intercomAppId: null,
        },
    });

export const loadInput: LoadExtensionInput = {
    shareId: 'share_example',
    recordId: null,
    context: { type: 'direct-url' },
    query: { prefill_Title: 'Example', repeated: ['First', 'Second'] },
    clientTimeZone: 'America/New_York',
    deviceFingerprint: { version: 1, visitorId: 'visitor_example' },
};

export const formResult: FormLoadedResult = {
    extensionScreen: 'form_loaded',
    extensionId: 'extension_example',
    language: 'en',
    themeColor: 'blue',
    enableCommentsOnChildForms: false,
    workspaceId: 'workspace_example',
    extensionOwnerUID: 'owner_example',
    faviconUrl: null,
    googleAnalyticsMeasurementId: null,
    isStarterExtension: false,
    publishedVersionId: 'version_example',
    payload: {
        extensionType: 'form',
        extensionAccessToken: 'access_example',
        extensionName: 'Example form',
        hasParentExtension: false,
        formRecord: { type: 'create', data: { fld_title: 'Example' } },
        formErrors: {},
        publicFields: publicFormFields(),
        fieldIdsInForm: ['fld_title'],
        fieldNamesToSchemas: {},
        fieldIdsToSchemas: {},
        formFieldIdsWithUnsavedChanges: ['fld_title'],
        urlPrefilledFieldIds: ['fld_title'],
        linkedRecordFieldIdToDetailFields: {},
        cookieKeyForLoginToken: null,
        baseId: 'base_example',
        loggedInUserCanEditExtension: false,
        showMiniExtensionsBranding: true,
        onFreePlan: true,
        trialExpiresAtUnixEpoch: null,
    },
};

export const saveInput: SaveFormInput = {
    extensionAccessToken: 'access_example',
    formRecord: { type: 'create', data: { fld_title: 'Updated example' } },
    formFieldIdsWithUnsavedChanges: ['fld_title'],
    captchaVal: null,
    isComputeMode: false,
    searchQuery: {},
    context: { type: 'direct-url' },
    conditionalLinkedRecordFieldIdsToFilteringValues: {},
    deviceFingerprint: { version: 1, visitorId: 'visitor_example' },
};
